spring.application.name=algatransito-api
#server.port=8080

spring.datasource.url=jdbc:mysql://localhost/algatransito?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Administrator
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#em producao desabilite, pois pode deixar a aplicacao mais pesada
spring.jpa.show-sql=true